config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get   'home/index'             
  get   'home/main' 
            

  root  'home#index'

  resources :players
  resources :pictures
  


  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  
  end

  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    cannot :manage, :all

    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      cannot :manage ,ActiveAdmin::Page
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
  

end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :file, PictureUploader
  belongs_to :player,optional: true
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :pictures
  accepts_nested_attributes_for :pictures, allow_destroy: true
end

app/models/player_registration.rb
class PlayerRegistration < ApplicationRecord
  has_many :pictures
  has_many :players
  
end

app/models/playerinfo.rb
class Playerinfo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  
  enum role: %i(user admin)
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  add_flash_types :success, :info, :warning, :danger

  def after_sign_in_path_for(resource)
    home_main_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  
  def index
    redirect_to '/home/main'
  end

  def main

  end



end

app/controllers/main_controller.rb
class MainController < ApplicationController

  before_action :authenticate_user!, only: :show
  
  def index
    render "layouts/main"
  end
  
  def show
  
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @picture = Picture.new
    @picture.save
  end
end

app/controllers/player_registration_controller.rb
class PlayerRegistrationController < ApplicationController
  protect_from_forgery with: :exception

  # def upload
  #   @picture = Picture.new( params.require(:picture).permit(:name, :file) )
  #   @picture.save

  #   @player = Player.new( params.require(:player).permit(:name, :number, :tall, :weight, :position))
  #   @player.save
  #   redirect_to action: 'index'
    
    
  # end


  def new
    @player_registration = PlayerRegistration.new
    @picture = Picture.new
    @player = Player.new
    @player.pictures.build

  end

  def create
    @player = Player.new(player_params)
    @player.save

  end

  def update
		@player_registrations.update(player_param)
		redirect_to root_path
	end

  private 
            # これは独特な書き方ですが、このように子要素のstrong parameterを書くことで
            # 自動で子要素に親要素のidもふられます。この場合だと、bookテーブルにあるuser_idにも
            # きちんとこの時作成される親要素のidがふられます。
        def player_params
            params.require(:picture).permit( :name, :number, :tall, :weight, :position,players_attribute: [:name, :name])
            
        end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  def index
    @players = Player.all
  end
  
  def new
    @player = Player.new
    @player.pictures.build

  end

  def create
    @player = Player.new(player_params)
    @player.save
    redirect_to player_path(id: @player.id)
  end

  def show
    @player = Player.find(params[:id])

  end

  # def update
	# 	@player_registrations.update(player_param)
	# 	redirect_to root_path
	# end

  private 
            # これは独特な書き方ですが、このように子要素のstrong parameterを書くことで
            # 自動で子要素に親要素のidもふられます。この場合だと、pictureテーブルにあるuser_idにも
            # きちんとこの時作成される親要素のidがふられます。
        def player_params
            params.require(:player).permit( :id, :name, :number, :tall, :weight, :position, pictures_attributes: [:file])
            
        end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/player_registration_helper.rb
module PlayerRegistrationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/home/index.html.erb
    <header>
      <nav>
        <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
        <% if user_signed_in? %> 
          <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
          <!-- *_path はUserモデルを作成したときに、
          deviseにより自動で作成されてますので、rake routesで確認できます -->
          
          <%= link_to '登録内容変更', edit_user_registration_path %> |
          <%= link_to "ログアウト", sign_out_path %>
        <% else %>
          <%= link_to "登録", new_user_registration_path %> |
          <%= link_to "ログイン", new_user_session_path %>
        <% end %>
        <br>

      </nav>
    </header>

  
    <% flash.each do |key, value| %>
      <% key = "info" if key == "notice" %>
      <% key = "danger"  if key == "alert" %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/home/main.html.erb
<%= link_to  "サインアウト", sign_out_path %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <nav class="navbar  navbar-default">
    <div  class="container">
      <ul class="nav  navbar-nav  ">
        <li  class="active"><a  href="#">HOME</a></li>
        <li  class="dropdown">
          <a href="#"  class="dropdown-toggle" data-toggle="dropdown"  role="button" aria-expanded="false">試合<span  class="caret"></span></a>
          <ul  class="dropdown-menu" role="menu">
            <li><a  href="#">試合</a></li>
            <li><a  href="/player_registration.html">選手一覧</a></li>
            <li><a  href="#">MUSIC</a></li>
            <li  class="divider"></li>
            <li><a  href="#">Separated link</a></li>
            <li  class="divider"></li>
            <li><a  href="#">One more separated link</a></li>
          </ul>
        </li>
        <li><a  href="/player/index.html">選手一覧</a></li>
        <li><a  href="/players/new">登録</a></li>
        <li><a  href="/admin/">管理</a></li>

      </ul>
    </div>


  </nav> 